FROM oven/bun:slim

# `openssl` is nodig voor OpenSSL 3.0.x beschikbaar te hebben
RUN apt-get update -y && apt-get install -y openssl curl

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install

COPY . .
COPY src/lib/prisma-client .

RUN bunx prisma generate

EXPOSE 5173

CMD ["bun", "run", "dev", "--host", "0.0.0.0"]